-- ============================================================================
-- LIVE FAMILY TRACKING — Pintu Angin v21
-- -----------------------------------------------------------------------------
-- Fitur: pendaki membuat sesi pelacakan → dapat link shareable → keluarga
--     melihat posisi real-time di peta. Tanpa perlu login bagi keluarga.
--
-- Tabel:
--   family_tracking_sessions — satu baris per sesi aktif, punya unique_link_token
--   family_tracking_positions — titik GPS per detik/detik (ringan, TTL auto-hapus)
--   family_tracking_subscribers — siapa saja yang subscribe push notifikasi
--
-- Keamanan:
--   - Pendaki wajib login (Supabase JWT)
--   - Link shareable bersifat random 32 karakter, tidak bisa ditebak
--   - Subscriber (keluarga) hanya butuh token dari link, tanpa login
--   - Sesi auto-expire setelah duration_max (default 6 jam)
--   - Pendaki bisa stop kapanpun
--
-- Jalankan sekali di Supabase → SQL Editor.
-- ============================================================================

-- ===== SESSIONS =====
create table if not exists public.family_tracking_sessions (
  id          uuid primary key default gen_random_uuid(),
  created_at  timestamptz not null default now(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  user_email  text not null,
  display_name text not null check (length(trim(display_name)) between 1 and 120),
  profile_pic text,
  
  -- Privacy & sharing
  link_token  text not null default replace(gen_random_uuid()::text, '-', '')
                check (length(link_token) = 62),
  is_active   boolean not null default true,
  is_paused   boolean not null default false,
  
  -- Session control
  auto_expire_at timestamptz,
  duration_hours int not null default 6 check (duration_hours >= 1 and duration_hours <= 24),
  stop_reason   text,
  
  -- Metadata (ringan, tidak selalu terisi)
  battery_pct   smallint check (battery_pct is null or (battery_pct >= 0 and battery_pct <= 100)),
  network_type  text check (network_type in ('4g','3g','2g','wifi','offline')),
  gps_accuracy_m  integer,
  
  constraint family_tracking_sessions_link_token_unique unique (link_token)
);

alter table public.family_tracking_sessions enable row level security;

-- Hanya pemilik yang bisa mengubah session-nya sendiri
create policy "owner reads own session"
  on public.family_tracking_sessions for select
  to authenticated
  using (user_id = auth.uid());

create policy "owner updates own session"
  on public.family_tracking_sessions for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- PUBLIC READ via token (untuk keluarga/subscriber)
create or replace function public.get_session_by_token(tok text)
returns table (
  id uuid,
  user_id uuid,
  user_email text,
  display_name text,
  profile_pic text,
  is_active boolean,
  is_paused boolean,
  auto_expire_at timestamptz,
  created_at timestamptz,
  battery_pct smallint,
  network_type text,
  gps_accuracy_m integer,
  last_position jsonb
) language plpgsql security definer set search_path=public
as $$
begin
  return query
  select 
    s.id, s.user_id, s.user_email, s.display_name, s.profile_pic,
    s.is_active, s.is_paused, s.auto_expire_at, s.created_at,
    s.battery_pct, s.network_type, s.gps_accuracy_m,
    (select p.position from public.family_tracking_positions p
     where p.session_id = s.id order by p.created_at desc limit 1) as last_position
  from public.family_tracking_sessions s
  where s.link_token = replace(tok, '-', '')
    and s.is_active = true
    and (s.auto_expire_at is null or s.auto_expire_at > now());
end;
$$;
revoke all on function public.get_session_by_token(text) from public;
grant execute on function public.get_session_by_token(text) to anon, authenticated;

-- ===== POSITIONS =====
create table if not exists public.family_tracking_positions (
  id          bigint generated by default as identity primary key,
  session_id  uuid not null references public.family_tracking_sessions(id) on delete cascade,
  created_at  timestamptz not null default now(),
  lat         double precision not null,
  lng         double precision not null,
  accuracy_m  integer default 10,
  altitude_m  integer,
  speed_kmh   double precision default 0,
  heading_deg integer,
  battery_pct smallint,
  network_type text,
  plus_code   text,
  is_offline  boolean not null default false,
  
  -- Index cepat untuk pembacaan posisi terbaru per session
  constraint family_tracking_positions_session_created unique (session_id, created_at)
);

create index if not exists ftp_session_created_idx
  on public.family_tracking_positions (session_id, created_at desc);

create index if not exists ftp_created_ttl_idx
  on public.family_tracking_positions (created_at)
  where created_at < now() - interval '25 hours';

-- RLS: tidak perlu policy publik. Posisi hanya bisa ditulis oleh API server
-- menggunakan service role key. Pengecekan session owner dilakukan di aplikasi.
alter table public.family_tracking_positions enable row level security;

-- Buat trigger hapus otomatis posisi lama (>24 jam)
create or replace function public.cleanup_old_positions()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
  delete from public.family_tracking_positions
  where created_at < now() - interval '24 hours';
  return new;
end;
$$;

drop trigger if exists trg_cleanup_positions on public.family_tracking_positions;
create trigger trg_cleanup_positions
  after insert on public.family_tracking_positions
  for each statement execute procedure public.cleanup_old_positions();

-- ===== SUBSCRIBERS =====
-- Keluarga yang subscribe push notifikasi untuk session tertentu
create table if not exists public.family_tracking_subscribers (
  id            uuid primary key default gen_random_uuid(),
  session_id    uuid not null references public.family_tracking_sessions(id) on delete cascade,
  subscriber_email text,
  subscriber_name text check (length(trim(subscriber_name)) between 1 and 120),
  subscription_json jsonb,
  notified_on   timestamptz not null default now(),
  created_at    timestamptz not null default now()
);

create index if not exists fts_session_idx
  on public.family_tracking_subscribers (session_id);

alter table public.family_tracking_subscribers enable row level security;

create policy "owner manages subscribers"
  on public.family_tracking_subscribers for all
  to authenticated
  using (
    session_id in (
      select id from public.family_tracking_sessions 
      where user_id = auth.uid()
    )
  );

-- ===== VIEW: posisi terakhir setiap session aktif =====
create or replace view public.v_latest_positions as
select 
  fs.id as session_id,
  fs.link_token,
  fs.display_name,
  fs.is_active,
  fs.is_paused,
  fs.battery_pct,
  fs.network_type,
  fs.gps_accuracy_m,
  fs.auto_expire_at,
  fs.created_at as session_created_at,
  ftp.lat,
  ftp.lng,
  ftp.accuracy_m,
  ftp.altitude_m,
  ftp.speed_kmh,
  ftp.heading_deg,
  ftp.plus_code,
  ftp.created_at as pos_at,
  floor(extract(epoch from now() - ftp.created_at) / 60) as minutes_ago
from public.family_tracking_sessions fs
join lateral (
  select lat, lng, accuracy_m, altitude_m, speed_kmh, heading_deg, plus_code, created_at
  from public.family_tracking_positions
  where session_id = fs.id
  order by created_at desc
  limit 1
) ftp on true
where fs.is_active = true
  and (fs.auto_expire_at is null or fs.auto_expire_at > now())
order by ftp.created_at desc;

-- ===== FUNCTION: delete expired sessions (bisa dipanggil manual atau cron) =====
create or replace function public.expire_old_sessions()
returns void language plpgsql security definer set search_path=public
as $$
begin
  update public.family_tracking_sessions
  set is_active = false, stop_reason = 'auto_expire'
  where is_active = true
    and auto_expire_at is not null
    and auto_expire_at < now();
end;
$$;
revoke all on function public.expire_old_sessions() from public;
grant execute on function public.expire_old_sessions() to anon, authenticated;

-- ===== INDEX TAMBAHAN UNTUK PERFORMA =====
create index if not exists fts_sessions_active_idx
  on public.family_tracking_sessions (is_active, is_paused, auto_expire_at)
  where is_active = true;

-- Catatan deploy:
-- 1. Jalankan SQL ini di Supabase SQL Editor
-- 2. Deploy API baru: api/family-tracking.js
-- 3. Tambahkan modul baru: family-tracking.js di client
-- 4. Tambahkan tombol/share di index.html
