/*
 * SOS Tracking mandiri.
 * Modul ini hanya membaca snapshot dari tracker.html dan TIDAK memanggil,
 * mengubah, atau bergantung pada sos.js / API SOS utama aplikasi.
 */
(function (global) {
  'use strict';
  var mounted=false;
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function snap(){var a=global.BWKTrackingView;return a?{pos:a.getLatest(),session:a.getSession(),positions:a.getPositions()}:{};}
  function when(p){var t=p&&(p.sent_at||p.at);return t?new Date(t).toLocaleString('id-ID')+' WITA':'Tidak tersedia';}
  function message(){var s=snap(),p=s.pos,n=s.session||{};return '🆘 *BANTUAN DARURAT — LIVE TRACKING*\n\nPendaki: '+(n.name||'Pendaki')+'\nPosisi: '+(p?p.lat.toFixed(6)+', '+p.lng.toFixed(6):'Belum tersedia')+'\nAkurasi: '+(p&&p.accuracy_m!=null?'±'+p.accuracy_m+' m':'—')+'\nElevasi: '+(p&&p.altitude_m!=null?p.altitude_m+' mdpl':'—')+'\nBaterai: '+(p&&p.battery_pct!=null?p.battery_pct+'%':'—')+'\nWaktu data: '+when(p)+'\n\nLink live: '+global.location.href+'\nGoogle Maps: '+(p?'https://www.google.com/maps?q='+p.lat+','+p.lng:'—')+'\n\n⚠️ Verifikasi kondisi pendaki dan hubungi petugas/112 bila benar darurat.';}
  function style(){if(document.getElementById('tkSosStyle'))return;var s=document.createElement('style');s.id='tkSosStyle';s.textContent=`
    .tk-sos-open{width:100%;min-height:48px;border-radius:14px;background:#fff;color:#b4232d;border:1px solid #efb6ba;font-weight:800;font-size:13px;box-shadow:0 4px 12px rgba(180,35,45,.08)}
    .tk-sos-open:focus-visible,.tk-sos-btn:focus-visible{outline:3px solid rgba(229,48,76,.28);outline-offset:2px}
    .tk-sos-modal{position:fixed;inset:0;z-index:10000;background:rgba(18,25,38,.66);display:none;align-items:flex-end;justify-content:center;padding:16px}.tk-sos-modal.open{display:flex}
    .tk-sos-sheet{width:min(448px,100%);background:#fff;border-radius:20px;padding:18px;box-shadow:0 18px 60px rgba(0,0,0,.3)}
    .tk-sos-head{display:flex;gap:12px;align-items:center}.tk-sos-icon{width:48px;height:48px;border-radius:14px;display:grid;place-items:center;background:#fdebec;color:#cc2635;font-size:24px}.tk-sos-head h2{font-size:18px;margin:0}.tk-sos-head p{font-size:11px;color:#687386;margin:2px 0 0}
    .tk-sos-note{margin:14px 0;background:#fff6e5;border:1px solid #f0d69e;border-radius:12px;padding:11px;font-size:12px;color:#714d08;line-height:1.5}
    .tk-sos-data{background:#f7f8fa;border-radius:12px;padding:11px;font-size:12px;line-height:1.65;color:#344054}
    .tk-sos-actions{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:13px}.tk-sos-btn{min-height:46px;border-radius:12px;border:1px solid #dfe3e9;background:#fff;font-size:12px;font-weight:800}.tk-sos-btn.red{background:#d92d3c;border-color:#d92d3c;color:#fff}.tk-sos-btn.green{background:#25d366;border-color:#25d366;color:#fff}.tk-sos-btn.wide{grid-column:1/-1}
    @media(prefers-reduced-motion:no-preference){.tk-sos-icon{animation:tkSosBeat 1.5s ease-in-out infinite}@keyframes tkSosBeat{0%,65%,100%{transform:scale(1)}73%{transform:scale(1.08)}82%{transform:scale(.98)}}}
  `;document.head.appendChild(s);}
  function mount(){if(mounted)return;var rows=document.querySelectorAll('.btn-row'),anchor=rows.length?rows[rows.length-1]:null;if(!anchor)return;style();var wrap=document.createElement('div');wrap.className='btn-row';wrap.innerHTML='<button type="button" class="tk-sos-open" id="tkSosOpen">🆘 Bantuan Darurat Tracking</button>';anchor.insertAdjacentElement('afterend',wrap);var modal=document.createElement('div');modal.id='tkSosModal';modal.className='tk-sos-modal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-labelledby','tkSosTitle');document.body.appendChild(modal);document.getElementById('tkSosOpen').onclick=open;modal.addEventListener('click',function(e){if(e.target===modal)close();});mounted=true;}
  function open(){var m=document.getElementById('tkSosModal'),s=snap(),p=s.pos,n=s.session||{};m.innerHTML='<div class="tk-sos-sheet"><div class="tk-sos-head"><div class="tk-sos-icon">🆘</div><div><h2 id="tkSosTitle">Bantuan Darurat Tracking</h2><p>Modul mandiri · tidak mengaktifkan SOS utama aplikasi</p></div></div><div class="tk-sos-note"><b>Gunakan hanya jika perlu.</b> Konfirmasi kondisi pendaki terlebih dahulu. Tombol ini menyiapkan dan membagikan data lokasi—tidak otomatis mengirim laporan ke sistem SOS aplikasi.</div><div class="tk-sos-data"><b>'+esc(n.name||'Pendaki')+'</b><br>📍 '+(p?esc(p.lat.toFixed(6)+', '+p.lng.toFixed(6)):'Lokasi belum tersedia')+'<br>🎯 '+(p&&p.accuracy_m!=null?'±'+esc(p.accuracy_m)+' m':'Akurasi —')+' · ⛰️ '+(p&&p.altitude_m!=null?esc(p.altitude_m)+' mdpl':'—')+'<br>🔋 '+(p&&p.battery_pct!=null?esc(p.battery_pct)+'%':'—')+' · 🕒 '+esc(when(p))+'</div><div class="tk-sos-actions"><button class="tk-sos-btn red" id="tkSosCall">☎ Hubungi 112</button><button class="tk-sos-btn green" id="tkSosWa">WhatsApp</button><button class="tk-sos-btn" id="tkSosMaps">Buka Maps</button><button class="tk-sos-btn" id="tkSosCopy">Salin paket</button><button class="tk-sos-btn wide" id="tkSosClose">Batal / Tutup</button></div></div>';m.classList.add('open');document.getElementById('tkSosCall').onclick=function(){if(confirm('Hubungi nomor darurat 112 sekarang?'))global.location.href='tel:112';};document.getElementById('tkSosWa').onclick=function(){global.open('https://wa.me/?text='+encodeURIComponent(message()),'_blank','noopener');};document.getElementById('tkSosMaps').onclick=function(){if(p)global.open('https://www.google.com/maps?q='+p.lat+','+p.lng,'_blank','noopener');else alert('Lokasi belum tersedia.');};document.getElementById('tkSosCopy').onclick=copy;document.getElementById('tkSosClose').onclick=close;}
  function close(){var m=document.getElementById('tkSosModal');if(m)m.classList.remove('open');}
  function copy(){var t=message();if(navigator.clipboard)navigator.clipboard.writeText(t).then(function(){alert('Paket darurat disalin.');}).catch(function(){fallback(t);});else fallback(t);}
  function fallback(t){var a=document.createElement('textarea');a.value=t;a.style.position='fixed';a.style.left='-9999px';document.body.appendChild(a);a.select();document.execCommand('copy');a.remove();alert('Paket darurat disalin.');}
  document.addEventListener('keydown',function(e){if(e.key==='Escape')close();});
  global.addEventListener('bwk:tracker-ready',mount);document.addEventListener('DOMContentLoaded',function(){setTimeout(mount,400);});
})(window);
